proxy_cache_path /var/run/nginx-cache keys_zone=mycache:100m;
proxy_cache_valid 200 304 3d;

server {
    listen 80;
		proxy_cache mycache;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
